#define IDO_ENGLISH                     0x0000
#define IDO_FRENCH                      0x0400
#define IDO_GERMAN                      0x0800

#define IDM_NONE                        0x4000
#define IDM_FILE_OPEN_GAME_EXE          0x4001
#define IDM_FILE_UPDATE_GAME_EXE        0x4002
#define IDM_FILE_OPEN_NAMES             0x4003
#define IDM_FILE_SAVE_NAMES             0x4004
#define IDM_FILE_IMPORT_GPE             0x4005
#define IDM_FILE_EXPORT_GPE             0x4006
#define IDM_LANGUAGE                    0x4007
#define IDM_EXIT                        0x4008
#define IDM_DESIGN_NEW                  0x4009
#define IDM_DESIGN_LOAD                 0x400a
#define IDM_DESIGN_SAVE                 0x400b
#define IDM_PERFORMANCE_CAR             0x400c
#define IDM_PERFORMANCE_DRIVER          0x400d
#define IDM_PERFORMANCE_DRIVING_AIDS    0x400e
#define IDM_PERFORMANCE_CAR_NUMBERS     0x400f
#define IDM_AI_CAR_GRIP                 0x4010
#define IDM_PLAYERS_CAR_PERFORMANCE     0x4011
#define IDM_NAMES                       0x4012
#define IDM_CAR_EDITOR                  0x4013
#define IDM_HELMET_EDITOR               0x4014
#define IDM_HELP_CONTENTS               0x4015
#define IDM_HELP_USE                    0x4016
#define IDM_ABOUT                       0x4017

#define IDD_ABOUT_GAME_EXE_VERSION      0x4000

#define IDD_CAR_PERF_TEAM_01            0x4000
#define IDD_CAR_PERF_TEAM_02            0x4001
#define IDD_CAR_PERF_TEAM_03            0x4002
#define IDD_CAR_PERF_TEAM_04            0x4003
#define IDD_CAR_PERF_TEAM_05            0x4004
#define IDD_CAR_PERF_TEAM_06            0x4005
#define IDD_CAR_PERF_TEAM_07            0x4006
#define IDD_CAR_PERF_TEAM_08            0x4007
#define IDD_CAR_PERF_TEAM_09            0x4008
#define IDD_CAR_PERF_TEAM_10            0x4009
#define IDD_CAR_PERF_TEAM_11            0x400a
#define IDD_CAR_PERF_TEAM_12            0x400b
#define IDD_CAR_PERF_TEAM_13            0x400c
#define IDD_CAR_PERF_TEAM_14            0x400d
#define IDD_CAR_PERF_TEAM_15            0x400e
#define IDD_CAR_PERF_TEAM_16            0x400f
#define IDD_CAR_PERF_TEAM_17            0x4010
#define IDD_CAR_PERF_TEAM_18            0x4011
#define IDD_CAR_PERF_TEAM_19            0x4012
#define IDD_CAR_PERF_TEAM_20            0x4013
#define IDD_CAR_PERF_SCROLL_01          0x4014
#define IDD_CAR_PERF_SCROLL_02          0x4015
#define IDD_CAR_PERF_SCROLL_03          0x4016
#define IDD_CAR_PERF_SCROLL_04          0x4017
#define IDD_CAR_PERF_SCROLL_05          0x4018
#define IDD_CAR_PERF_SCROLL_06          0x4019
#define IDD_CAR_PERF_SCROLL_07          0x401a
#define IDD_CAR_PERF_SCROLL_08          0x401b
#define IDD_CAR_PERF_SCROLL_09          0x401c
#define IDD_CAR_PERF_SCROLL_10          0x401d
#define IDD_CAR_PERF_SCROLL_11          0x401e
#define IDD_CAR_PERF_SCROLL_12          0x401f
#define IDD_CAR_PERF_SCROLL_13          0x4020
#define IDD_CAR_PERF_SCROLL_14          0x4021
#define IDD_CAR_PERF_SCROLL_15          0x4022
#define IDD_CAR_PERF_SCROLL_16          0x4023
#define IDD_CAR_PERF_SCROLL_17          0x4024
#define IDD_CAR_PERF_SCROLL_18          0x4025
#define IDD_CAR_PERF_SCROLL_19          0x4026
#define IDD_CAR_PERF_SCROLL_20          0x4027
#define IDD_CAR_PERF_POWER_01           0x4028
#define IDD_CAR_PERF_POWER_02           0x4029
#define IDD_CAR_PERF_POWER_03           0x402a
#define IDD_CAR_PERF_POWER_04           0x402b
#define IDD_CAR_PERF_POWER_05           0x402c
#define IDD_CAR_PERF_POWER_06           0x402d
#define IDD_CAR_PERF_POWER_07           0x402e
#define IDD_CAR_PERF_POWER_08           0x402f
#define IDD_CAR_PERF_POWER_09           0x4030
#define IDD_CAR_PERF_POWER_10           0x4031
#define IDD_CAR_PERF_POWER_11           0x4032
#define IDD_CAR_PERF_POWER_12           0x4033
#define IDD_CAR_PERF_POWER_13           0x4034
#define IDD_CAR_PERF_POWER_14           0x4035
#define IDD_CAR_PERF_POWER_15           0x4036
#define IDD_CAR_PERF_POWER_16           0x4037
#define IDD_CAR_PERF_POWER_17           0x4038
#define IDD_CAR_PERF_POWER_18           0x4039
#define IDD_CAR_PERF_POWER_19           0x403a
#define IDD_CAR_PERF_POWER_20           0x403b
#define IDD_CAR_PERF_HELP               0x403c
#define IDD_CAR_PERF_SCROLL_ALL         0x403d
#define IDD_CAR_PERF_EQUAL_BHP          0x403e

#define IDD_DRIVER_PERF_DRIVER          0x4000
#define IDD_DRIVER_PERF_QUALIFYING      0x4001
#define IDD_DRIVER_PERF_QUALIFYING_TXT  0x4002
#define IDD_DRIVER_PERF_RACE            0x4003
#define IDD_DRIVER_PERF_RACE_TXT        0x4004
#define IDD_DRIVER_PERF_HELP            0x4005

#define IDD_DRIVER_AID_ROOKIE           0x4000
#define IDD_DRIVER_AID_AMATEUR          0x4001
#define IDD_DRIVER_AID_SEMIPRO          0x4002
#define IDD_DRIVER_AID_PRO              0x4003
#define IDD_DRIVER_AID_ACE              0x4004
#define IDD_DRIVER_AID_AUTO_BRAKES      0x4005
#define IDD_DRIVER_AID_AUTO_GEARS       0x4006
#define IDD_DRIVER_AID_SPIN             0x4007
#define IDD_DRIVER_AID_DAMAGE           0x4008
#define IDD_DRIVER_AID_BEST_LINE        0x4009
#define IDD_DRIVER_AID_GEAR_IND         0x400a
#define IDD_DRIVER_AID_F1               0x400b
#define IDD_DRIVER_AID_F2               0x400c
#define IDD_DRIVER_AID_F3               0x400d
#define IDD_DRIVER_AID_F4               0x400e
#define IDD_DRIVER_AID_F5               0x400f
#define IDD_DRIVER_AID_F6               0x4010
#define IDD_DRIVER_AID_ALLOW_ALL        0x4011
#define IDD_DRIVER_AID_NORMAL           0x4012

#define IDD_CAR_NUMBER_LIST1            0x4000
#define IDD_CAR_NUMBER_LIST2            0x4001
#define IDD_CAR_NUMBER_NORMAL           0x4002
#define IDD_CAR_NUMBER_TXT_01           0x4003
#define IDD_CAR_NUMBER_TXT_02           0x4004
#define IDD_CAR_NUMBER_TXT_03           0x4005
#define IDD_CAR_NUMBER_TXT_04           0x4006
#define IDD_CAR_NUMBER_TXT_05           0x4007
#define IDD_CAR_NUMBER_TXT_06           0x4008
#define IDD_CAR_NUMBER_TXT_07           0x4009
#define IDD_CAR_NUMBER_TXT_08           0x400a
#define IDD_CAR_NUMBER_TXT_09           0x400b
#define IDD_CAR_NUMBER_TXT_10           0x400c
#define IDD_CAR_NUMBER_TXT_11           0x400d
#define IDD_CAR_NUMBER_TXT_12           0x400e
#define IDD_CAR_NUMBER_TXT_13           0x400f
#define IDD_CAR_NUMBER_TXT_14           0x4010
#define IDD_CAR_NUMBER_TXT_15           0x4011
#define IDD_CAR_NUMBER_TXT_16           0x4012
#define IDD_CAR_NUMBER_TXT_17           0x4013
#define IDD_CAR_NUMBER_TXT_18           0x4014
#define IDD_CAR_NUMBER_TXT_19           0x4015
#define IDD_CAR_NUMBER_TXT_20           0x4016
#define IDD_CAR_NUMBER_RB_01            0x4017
#define IDD_CAR_NUMBER_RB_02            0x4018
#define IDD_CAR_NUMBER_RB_03            0x4019
#define IDD_CAR_NUMBER_RB_04            0x401a
#define IDD_CAR_NUMBER_RB_05            0x401b
#define IDD_CAR_NUMBER_RB_06            0x401c
#define IDD_CAR_NUMBER_RB_07            0x401d
#define IDD_CAR_NUMBER_RB_08            0x401e
#define IDD_CAR_NUMBER_RB_09            0x401f
#define IDD_CAR_NUMBER_RB_10            0x4020
#define IDD_CAR_NUMBER_RB_11            0x4021
#define IDD_CAR_NUMBER_RB_12            0x4022
#define IDD_CAR_NUMBER_RB_13            0x4023
#define IDD_CAR_NUMBER_RB_14            0x4024
#define IDD_CAR_NUMBER_RB_15            0x4025
#define IDD_CAR_NUMBER_RB_16            0x4026
#define IDD_CAR_NUMBER_RB_17            0x4027
#define IDD_CAR_NUMBER_RB_18            0x4028
#define IDD_CAR_NUMBER_RB_19            0x4029
#define IDD_CAR_NUMBER_RB_20            0x402a

#define IDD_LANGUAGE_RB_ENGLISH         0x4000
#define IDD_LANGUAGE_RB_FRENCH          0x4001
#define IDD_LANGUAGE_RB_GERMAN          0x4002

#define IDD_GPE_IMP_COMMENT            0x4000
#define IDD_GPE_IMP_COMMENT_SAVE       0x4001

#define IDD_GPE_EXP_COMMENT             0x4000
#define IDD_GPE_EXP_COMMENT_LOAD        0x4001

#define IDD_NAMES_TEAM                  0x4000
#define IDD_NAMES_ENGINE                0x4001
#define IDD_NAMES_DRIVER1               0x4002
#define IDD_NAMES_DRIVER2               0x4003
#define IDD_NAMES_DRIVER1_TEXT          0x4004
#define IDD_NAMES_DRIVER2_TEXT          0x4005

#define IDD_AI_CAR_GRIP_SB              0x4000
#define IDD_AI_CAR_GRIP_TEXT            0x4001
#define IDD_AI_CAR_GRIP_NORMAL          0x4002

#define IDD_PLAYERS_CAR_PERF_SB         0x4000
#define IDD_PLAYERS_CAR_PERF_TEXT       0x4001
#define IDD_PLAYERS_CAR_PERF_NORMAL     0x4002

#define IDE_CBAR_CANCEL_DROPDOWN        (WM_USER +  1)
#define IDE_CBAR_SHOW_TEAMS             (WM_USER +  2)
#define IDE_CBAR_TEAM_SELECT            (WM_USER +  3)
#define IDE_CBAR_DRIVER_SELECT          (WM_USER +  4)
#define IDE_CBAR_LOAD_NAMES             (WM_USER +  5)
#define IDE_CBAR_SHOW_DRIVERS           (WM_USER +  6)
#define IDE_CBAR_LOAD_DRIVERS           (WM_USER +  7)
#define IDE_CBAR_LOAD_DRIVER_NAMES      (WM_USER +  8)
#define IDE_DESIGN_NEW                  (WM_USER +  9)
#define IDE_DESIGN_LOAD                 (WM_USER + 10)
#define IDE_DESIGN_SAVE                 (WM_USER + 11)
#define IDE_DESIGN_NEW_PALETTE_COLOUR   (WM_USER + 12)
#define IDE_DESIGN_LOAD_EXE_COLOURS     (WM_USER + 13)
#define IDE_DESIGN_SAVE_EXE_COLOURS     (WM_USER + 14)
#define IDE_DESIGN_TEAM_SELECT          (WM_USER + 15)
#define IDE_TEAMS_TEAM_SELECT           (WM_USER + 16)
#define IDE_TEAMS_UPDATE_ALL_CARS       (WM_USER + 17)
#define IDE_HELMET_NEW_PALETTE_COLOUR   (WM_USER + 18)
#define IDE_HELMET_NEW                  (WM_USER + 19)
#define IDE_HELMET_LOAD                 (WM_USER + 20)
#define IDE_HELMET_SAVE                 (WM_USER + 21)
#define IDE_HELMET_LOAD_EXE_COLOURS     (WM_USER + 22)
#define IDE_HELMET_SAVE_EXE_COLOURS     (WM_USER + 23)
#define IDE_HELMET_DRIVER_SELECT        (WM_USER + 24)

#define IDT_APP_NAME                    0x5000
#define IDT_YOU_NEED_A_MOUSE            0x5001
#define IDT_OPEN_GAME_EXE_DLG_TITLE     0x5002
#define IDT_INVALID_GAME_EXE            0x5003
#define IDT_UNABLE_TO_OPEN              0x5004
#define IDT_UNKNOWN_GAME_VERSION        0x5005
#define IDT_ENSURE_GAME_EXE_BACKED_UP   0x5006
#define IDT_WRITE_FAILED                0x5007
#define IDT_READ_FAILED                 0x5008
#define IDT_SUCCESSFULLY_UPDATED        0x5009
#define IDT_OPEN_NAMES_DLG_TITLE        0x500a
#define IDT_SAVE_NAMES_DLG_TITLE        0x500b
#define IDT_OPEN_CAR_DESIGN_DLG_TITLE   0x500c
#define IDT_SAVE_CAR_DESIGN_DLG_TITLE   0x500d
#define IDT_OVERWRITE_EXISTING_FILE     0x500e
#define IDT_ABOUT_GAME_EXE_VERSION      0x500f
#define IDT_OPEN_HELMET_DLG_TITLE       0x5010
#define IDT_SAVE_HELMET_DLG_TITLE       0x5011
#define IDT_NOT_F1_HELMET_FILE          0x5012
#define IDT_NOT_F1_DESIGN_FILE          0x5013
#define IDT_IMPORT_GPE_DLG_TITLE        0x5014
#define IDT_EXPORT_GPE_DLG_TITLE        0x5015
#define IDT_INVALID_GPE_FILE            0x5016
#define IDT_LANGUAGE                    0x5017
#define IDT_CANCEL                      0x5018
#define IDT_CAR                         0x5019
#define IDT_HELMET                      0x501a
#define IDT_COMDLG_FILE_TEMPLATE_EXE    0x501b
#define IDT_COMDLG_FILE_TEMPLATE_GPE    0x501c
#define IDT_COMDLG_FILE_TEMPLATE_NAM    0x501d
#define IDT_COMDLG_FILE_TEMPLATE_CAR    0x501e
#define IDT_COMDLG_FILE_TEMPLATE_HEL    0x501f
#define IDT_COMDLG_FILE_TEMPLATE_TXT    0x5020
#define IDT_EUROPEAN                    0x5021
#define IDT_DRIVER                      0x5022
#define IDT_TEAM                        0x5023
#define IDT_GPE_SAVE_COMMENT_DLG_TITLE  0x5024
#define IDT_GPE_LOAD_COMMENT_DLG_TITLE  0x5025

#define IDT_OUT_OF_MEMORY               0x6000
#define IDT_UNABLE_TO_REGISTER_CLASS    0x6001
#define IDT_UNABLE_TO_LOAD_BITMAP       0x6002
#define IDT_UNABLE_TO_CREATE_PALETTE    0x6003

#define IDR_TOOLBAR                     999 /*<TK >*/

#include "helpids.h"
