!if !$d(CPPWIN_INC)
!error CPPWIN_INC env variable not set!
!endif

!include "$(CPPWIN_INC)\makefile.cmn"

TARGET =       toolbar

.cpp.obj:
               $(CPP) @&&!
                    $(CPPFLAGS_CMN) -UWINVER -v $(CPPFLAGS) -H=$(TARGET).pch -DSTRICT $<
!

OBJ =          toolbar.obj
OBJ_LIB =      +-toolbar.obj
HDR =          toolbar.hpp

all:           $(TARGET).$(LIBTYPE)

turboc.cfg:    makefile
               echo -II:\INCLUDE        >  turboc.cfg 
               echo -LI:\LIB            >> turboc.cfg
               echo -I$(INCLUDE_PATH)   >> turboc.cfg

toolbar.obj:  toolbar.cpp $(HDR) version.ipp

$(TARGET).$(LIBTYPE): turboc.cfg $(OBJ) makefile
               $(LIB) $(TARGET).$(LIBTYPE) @&&!
                    $(OBJ_LIB)
!
               if exist *.bak del *.bak
