##
## Computer Car's Pit Strategy TSR for MPS GP.EXE
##

CC             =    bcc
CC_FLAGS       =    -v -c -y -O2 -1 -u- -w
ASM            =    tasm
ASM_FLAGS      =    -Ml -zd -zi
LINK           =    tlink /l /m /s /c /Tde
EXE2BIN        =    exe2bin

##                                    Code class/segment  Data class/group/segment    BSS class/group/segment
CC_RESIDENT    =    $(CC) $(CC_FLAGS) -zACODE -zCTSR_CODE -zTDATA -zSTSR -zRTSR_DATA  -zBDATA -zGTSR -zDTSR_DATA 
CC_TRANSIENT   =    $(CC) $(CC_FLAGS) -zATMP  -zCTSR_TMP  -zTTMP  -zSTSR  -zRTSR_TMP  -zBTMP  -zGTSR  -zDTSR_TMP  

##
## Note: endres.obj *must* be last!
##
OBJS           =    gpbutton.obj install.obj int08.obj int11.obj parse.obj \
                    endres.obj

.asm.obj:      
               $(ASM) $< $(ASM_FLAGS),,;

all:           gpbutton.exe

gpbutton.obj:  gpbutton.asm segments.inc gpbutton.inc

install.obj:   install.asm segments.inc gpbutton.inc

int08.obj:     int08.asm segments.inc gpbutton.inc

int11.obj:     int11.asm segments.inc gpbutton.inc

parse.obj:     parse.c gpbutton.h version.i
               $(CC_TRANSIENT) parse.c 

endres.obj:    endres.asm segments.inc

gpbutton.exe:  $(OBJS) makefile
               $(LINK) @&&!
                    $(OBJS),gpbutton;
!
               msym gpbutton

zip:           
               if exist gpbutton.zip del gpbutton.zip
               pkzip gpbutton gpbutton.txt gpbutton.exe

buildall:      all
